; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=m68k-linux | FileCheck %s

; Function Attrs: norecurse nounwind readnone
define zeroext i1 @c_isspace(i32 %c) local_unnamed_addr #0 {
; CHECK-LABEL: c_isspace:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    move.l (4,%sp), %d1
; CHECK-NEXT:    add.l #-9, %d1
; CHECK-NEXT:    and.l #16777215, %d1
; CHECK-NEXT:    move.l #8388639, %d0
; CHECK-NEXT:    lsr.l %d1, %d0
; CHECK-NEXT:    and.l #1, %d0
; CHECK-NEXT:    rts
entry:
  %switch.tableidx = add i32 %c, -9
  %switch.cast = trunc i32 %switch.tableidx to i24
  %switch.downshift = lshr i24 -8388577, %switch.cast
  %0 = and i24 %switch.downshift, 1
  %switch.masked = icmp ne i24 %0, 0
  ret i1 %switch.masked
}
