; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple aarch64-unknown-linux-musl -O0 -global-isel-abort=2 < %s 2>&1 | FileCheck %s --check-prefix=CHECK-LE
; RUN: llc -mtriple aarch64_be-unknown-linux-musl -O0 -global-isel-abort=2 < %s 2>&1 | FileCheck %s --check-prefix=CHECK-BE

; Make sure we fall-back to SDAG for BE targets.

; CHECK-LE-NOT: warning: Instruction selection used fallback path for foo
; CHECK-BE: warning: Instruction selection used fallback path for foo

define <4 x i6> @foo(float %0, <4 x i6> %1) {
; CHECK-LE-LABEL: foo:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    fmov d0, d1
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: foo:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    fmov d0, d1
; CHECK-BE-NEXT:    ret
  ret <4 x i6> %1
}
