; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple aarch64-unknown-linux -S < %s | FileCheck --check-prefix=NOPAUTH %s
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple aarch64-unknown-linux -mattr=+pauth -S < %s | FileCheck --check-prefix=PAUTH1 %s
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple arm64e-apple-darwin -S < %s | FileCheck --check-prefix=PAUTH2 %s

@ds = external global i8

define i64 @sign1(i64 %p) {
; NOPAUTH-LABEL: define i64 @sign1(
; NOPAUTH-SAME: i64 [[P:%.*]]) {
; NOPAUTH-NEXT:    [[TMP1:%.*]] = call i64 @__emupac_autda(i64 [[P]], i64 1)
; NOPAUTH-NEXT:    ret i64 [[TMP1]]
;
; PAUTH1-LABEL: define i64 @sign1(
; PAUTH1-SAME: i64 [[P:%.*]]) #[[ATTR0:[0-9]+]] {
; PAUTH1-NEXT:    [[SIGNED:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]], i32 2, i64 1)
; PAUTH1-NEXT:    ret i64 [[SIGNED]]
;
; PAUTH2-LABEL: define i64 @sign1(
; PAUTH2-SAME: i64 [[P:%.*]]) {
; PAUTH2-NEXT:    [[SIGNED:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]], i32 2, i64 1)
; PAUTH2-NEXT:    ret i64 [[SIGNED]]
;
  %signed = call i64 @llvm.ptrauth.auth(i64 %p, i32 2, i64 1)
  ret i64 %signed
}
define i64 @sign2(i64 %p) {
; NOPAUTH-LABEL: define i64 @sign2(
; NOPAUTH-SAME: i64 [[P:%.*]]) {
; NOPAUTH-NEXT:    [[TMP1:%.*]] = call i64 @__emupac_autda(i64 [[P]], i64 1) [ "deactivation-symbol"(ptr @ds) ]
; NOPAUTH-NEXT:    ret i64 [[TMP1]]
;
; PAUTH1-LABEL: define i64 @sign2(
; PAUTH1-SAME: i64 [[P:%.*]]) #[[ATTR0]] {
; PAUTH1-NEXT:    [[SIGNED:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]], i32 2, i64 1) [ "deactivation-symbol"(ptr @ds) ]
; PAUTH1-NEXT:    ret i64 [[SIGNED]]
;
; PAUTH2-LABEL: define i64 @sign2(
; PAUTH2-SAME: i64 [[P:%.*]]) {
; PAUTH2-NEXT:    [[SIGNED:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]], i32 2, i64 1) [ "deactivation-symbol"(ptr @ds) ]
; PAUTH2-NEXT:    ret i64 [[SIGNED]]
;
  %signed = call i64 @llvm.ptrauth.auth(i64 %p, i32 2, i64 1) [ "deactivation-symbol"(ptr @ds) ]
  ret i64 %signed
}
define i64 @sign3(i64 %p) {
; NOPAUTH-LABEL: define i64 @sign3(
; NOPAUTH-SAME: i64 [[P:%.*]]) {
; NOPAUTH-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]], i32 0, i64 1) [ "deactivation-symbol"(ptr @ds) ]
; NOPAUTH-NEXT:    ret i64 [[TMP1]]
;
; PAUTH1-LABEL: define i64 @sign3(
; PAUTH1-SAME: i64 [[P:%.*]]) #[[ATTR0]] {
; PAUTH1-NEXT:    [[SIGNED:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]], i32 0, i64 1) [ "deactivation-symbol"(ptr @ds) ]
; PAUTH1-NEXT:    ret i64 [[SIGNED]]
;
; PAUTH2-LABEL: define i64 @sign3(
; PAUTH2-SAME: i64 [[P:%.*]]) {
; PAUTH2-NEXT:    [[SIGNED:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]], i32 0, i64 1) [ "deactivation-symbol"(ptr @ds) ]
; PAUTH2-NEXT:    ret i64 [[SIGNED]]
;
  %signed = call i64 @llvm.ptrauth.auth(i64 %p, i32 0, i64 1) [ "deactivation-symbol"(ptr @ds) ]
  ret i64 %signed
}
