; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes
; RUN: opt -S -passes=function-attrs < %s | FileCheck %s

define void @f() {
; CHECK: Function Attrs: nofree nosync nounwind
; CHECK-LABEL: define {{[^@]+}}@f
; CHECK-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    call void @g() [ "unknown"() ]
; CHECK-NEXT:    ret void
;
  call void @g() [ "unknown"() ]
  ret void
}

define void @g() {
; CHECK: Function Attrs: nofree nosync nounwind
; CHECK-LABEL: define {{[^@]+}}@g
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    ret void
;
  call void @f()
  ret void
}
