// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-windows -fasync-exceptions -fms-compatibility %s -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local i32 @a(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] personality ptr @__C_specific_handler {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[__EXCEPTION_CODE:%.*]] = alloca i32, align 4
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[CATCH_DISPATCH:.*]]
// CHECK:       [[INVOKE_CONT]]:
// CHECK-NEXT:    [[TMP0:%.*]] = load volatile i32, ptr [[B]], align 4
// CHECK-NEXT:    invoke void @llvm.seh.try.end()
// CHECK-NEXT:            to label %[[INVOKE_CONT1:.*]] unwind label %[[CATCH_DISPATCH]]
// CHECK:       [[CATCH_DISPATCH]]:
// CHECK-NEXT:    [[TMP1:%.*]] = catchswitch within none [label %[[__EXCEPT_RET:.*]]] unwind to caller
// CHECK:       [[__EXCEPT_RET]]:
// CHECK-NEXT:    [[TMP2:%.*]] = catchpad within [[TMP1]] [ptr @"?filt$0@0@a@@"]
// CHECK-NEXT:    catchret from [[TMP2]] to label %[[__EXCEPT:.*]]
// CHECK:       [[__EXCEPT]]:
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.eh.exceptioncode(token [[TMP2]])
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[__EXCEPTION_CODE]], align 4
// CHECK-NEXT:    br label %[[__TRY_CONT:.*]]
// CHECK:       [[__TRY_CONT]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[RETVAL]], align 4
// CHECK-NEXT:    ret i32 [[TMP4]]
// CHECK:       [[INVOKE_CONT1]]:
// CHECK-NEXT:    br label %[[__TRY_CONT]]
//
long a() {
  long b;
  __try {
    b;
  } __except (a()) {
  }
}
