; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals --version 3
; RUN: opt -mtriple=i686-unknown-linux -S -passes=lowertypetests -lowertypetests-summary-action=import -lowertypetests-read-summary=%S/Inputs/import.yaml %s | FileCheck %s

declare i1 @llvm.type.test(ptr %ptr, metadata %bitset) nounwind readnone


;.
; CHECK: @__typeid_allones32_global_addr = external hidden global [0 x i8], code_model "small"
; CHECK: @__typeid_allones32_align = external hidden global [0 x i8], !absolute_symbol [[META0:![0-9]+]]
; CHECK: @__typeid_allones32_size_m1 = external hidden global [0 x i8], !absolute_symbol [[META1:![0-9]+]]
; CHECK: @__typeid_allones7_global_addr = external hidden global [0 x i8], code_model "small"
; CHECK: @__typeid_allones7_align = external hidden global [0 x i8], !absolute_symbol [[META0]]
; CHECK: @__typeid_allones7_size_m1 = external hidden global [0 x i8], !absolute_symbol [[META2:![0-9]+]]
;.
define i1 @allones7(ptr %p) {
; CHECK-LABEL: define i1 @allones7(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[P]] to i32
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 ptrtoint (ptr @__typeid_allones7_global_addr to i32), [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.fshr.i32(i32 [[TMP2]], i32 [[TMP2]], i32 ptrtoint (ptr @__typeid_allones7_align to i32))
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ule i32 [[TMP3]], ptrtoint (ptr @__typeid_allones7_size_m1 to i32)
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %x = call i1 @llvm.type.test(ptr %p, metadata !"allones7")
  ret i1 %x
}

define i1 @allones32(ptr %p) {
; CHECK-LABEL: define i1 @allones32(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[P]] to i32
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 ptrtoint (ptr @__typeid_allones32_global_addr to i32), [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.fshr.i32(i32 [[TMP2]], i32 [[TMP2]], i32 ptrtoint (ptr @__typeid_allones32_align to i32))
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ule i32 [[TMP3]], ptrtoint (ptr @__typeid_allones32_size_m1 to i32)
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %x = call i1 @llvm.type.test(ptr %p, metadata !"allones32")
  ret i1 %x
}
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
;.
; CHECK: [[META0]] = !{i32 0, i32 256}
; CHECK: [[META1]] = !{i32 -1, i32 -1}
; CHECK: [[META2]] = !{i32 0, i32 128}
;.
