# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            ptrmask_p0_s64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10, $x11
    ; CHECK-LABEL: name: ptrmask_p0_s64
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AND:%[0-9]+]]:gpr = AND [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[AND]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s64) = COPY $x11
    %2:gprb(p0) = G_PTRMASK %0(p0), %1(s64)
    $x10 = COPY %2(p0)
    PseudoRET implicit $x10
...

---
name:            ptrmask_p0_const_s64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: ptrmask_p0_const_s64
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[ANDI:%[0-9]+]]:gpr = ANDI [[COPY]], 10
    ; CHECK-NEXT: $x10 = COPY [[ANDI]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s64) = G_CONSTANT i64 10
    %2:gprb(p0) = G_PTRMASK %0(p0), %1(s64)
    $x10 = COPY %2(p0)
    PseudoRET implicit $x10
...
