; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='cgscc(inline),rpo-function-attrs' < %s | FileCheck %s

; Check that invalid nofpclass attributes aren't added to the return
; of called_in_unreachable_code. This would only occur due to stale
; edges in LazyCallGraph. When the inliner prunes the unreachadle code
; in calls_unreachable, the call graph edge to
; called_in_unreachable_code remains.

@global = external global i64


define i32 @external_caller() {
; CHECK-LABEL: define i32 @external_caller() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 0
;
entry:
  %call20 = call i32 @calls_unreachable()
  ret i32 %call20
}

define internal i32 @calls_unreachable() {
entry:
  br label %ret

unreachable:                                        ; No predecessors!
  %dead = call i64 @called_in_unreachable_code()
  br label %ret

ret:
  ret i32 0
}

define internal i64 @called_in_unreachable_code() {
; CHECK-LABEL: define internal i64 @called_in_unreachable_code() {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[ALLOCA:%.*]] = alloca i64, align 8
; CHECK-NEXT:    store i64 0, ptr @global, align 8
; CHECK-NEXT:    [[LOAD:%.*]] = load i64, ptr @global, align 8
; CHECK-NEXT:    [[ICMP:%.*]] = icmp sgt i64 [[LOAD]], 0
; CHECK-NEXT:    br i1 [[ICMP]], label %[[BB1:.*]], label %[[BB7:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[LOAD2:%.*]] = load i64, ptr @global, align 8
; CHECK-NEXT:    [[ICMP3:%.*]] = icmp sgt i64 [[LOAD2]], 0
; CHECK-NEXT:    [[LOAD4:%.*]] = load i64, ptr @global, align 8
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 0, [[LOAD4]]
; CHECK-NEXT:    [[LOAD5:%.*]] = load i64, ptr @global, align 8
; CHECK-NEXT:    [[ICMP6:%.*]] = icmp sgt i64 [[LOAD5]], 0
; CHECK-NEXT:    ret i64 0
; CHECK:       [[BB7]]:
; CHECK-NEXT:    [[LOAD8:%.*]] = load i64, ptr @global, align 8
; CHECK-NEXT:    [[ICMP9:%.*]] = icmp slt i64 [[LOAD8]], 0
; CHECK-NEXT:    [[LOAD10:%.*]] = load i64, ptr @global, align 8
; CHECK-NEXT:    ret i64 [[LOAD10]]
;
bb:
  %alloca = alloca i64, align 8
  store i64 0, ptr @global, align 8
  %load = load i64, ptr @global, align 8
  %icmp = icmp sgt i64 %load, 0
  br i1 %icmp, label %bb1, label %bb7

bb1:                                              ; preds = %bb
  %load2 = load i64, ptr @global, align 8
  %icmp3 = icmp sgt i64 %load2, 0
  %load4 = load i64, ptr @global, align 8
  %sub = sub i64 0, %load4
  %load5 = load i64, ptr @global, align 8
  %icmp6 = icmp sgt i64 %load5, 0
  ret i64 0

bb7:                                              ; preds = %bb
  %load8 = load i64, ptr @global, align 8
  %icmp9 = icmp slt i64 %load8, 0
  %load10 = load i64, ptr @global, align 8
  ret i64 %load10
}
