; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare float @llvm.round.f32(float)
declare double @llvm.roundeven.f64(double)

define float @intrinsic_roundeven_f32(float %x) {
; CHECK-LABEL: intrinsic_roundeven_f32:
; CHECK:         .functype intrinsic_roundeven_f32 (f32) -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    f32.nearest $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call float @llvm.roundeven.f32(float %x)
  ret float %a
}

define double @intrinsic_roundeven_f64(double %x) {
; CHECK-LABEL: intrinsic_roundeven_f64:
; CHECK:         .functype intrinsic_roundeven_f64 (f64) -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    f64.nearest $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call double @llvm.roundeven.f64(double %x)
  ret double %a
}
