; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i8 @srem_i8(i8 %x, i8 %y) {
; CHECK-LABEL: srem_i8:
; CHECK:         .functype srem_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.extend8_s $push0=, $pop3
; CHECK-NEXT:    local.get $push4=, 1
; CHECK-NEXT:    i32.extend8_s $push1=, $pop4
; CHECK-NEXT:    i32.rem_s $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = srem i8 %x, %y
  ret i8 %a
}

define i16 @srem_i16(i16 %x, i16 %y) {
; CHECK-LABEL: srem_i16:
; CHECK:         .functype srem_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.extend16_s $push0=, $pop3
; CHECK-NEXT:    local.get $push4=, 1
; CHECK-NEXT:    i32.extend16_s $push1=, $pop4
; CHECK-NEXT:    i32.rem_s $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = srem i16 %x, %y
  ret i16 %a
}

define i32 @srem_i32(i32 %x, i32 %y) {
; CHECK-LABEL: srem_i32:
; CHECK:         .functype srem_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.rem_s $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = srem i32 %x, %y
  ret i32 %a
}

define i64 @srem_i64(i64 %x, i64 %y) {
; CHECK-LABEL: srem_i64:
; CHECK:         .functype srem_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.rem_s $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = srem i64 %x, %y
  ret i64 %a
}
