; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-revec -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define void @test(<16 x i1> %0) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: <16 x i1> [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <16 x i16> [ zeroinitializer, %[[ENTRY]] ], [ [[TMP2:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI40:%.*]] = phi <16 x i16> [ zeroinitializer, %[[ENTRY]] ], [ [[TMP4:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 false, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer
; CHECK-NEXT:    [[TMP2]] = mul <16 x i16> zeroinitializer, [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = select <16 x i1> [[TMP0]], <16 x i16> zeroinitializer, <16 x i16> zeroinitializer
; CHECK-NEXT:    [[TMP4]] = mul <16 x i16> [[TMP3]], zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY]]
;
entry:
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %vec.phi = phi <16 x i16> [ zeroinitializer, %entry ], [ %2, %vector.body ]
  %vec.phi40 = phi <16 x i16> [ zeroinitializer, %entry ], [ %4, %vector.body ]
  %1 = select i1 false, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer
  %2 = mul <16 x i16> zeroinitializer, %1
  %3 = select <16 x i1> %0, <16 x i16> zeroinitializer, <16 x i16> zeroinitializer
  %4 = mul <16 x i16> %3, zeroinitializer
  br label %vector.body
}
