; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -p loop-vectorize -S %s | FileCheck %s

target triple = "arm64-apple-macosx"

define void @test_predicated_store(ptr %src, ptr %dst) #0 {
; CHECK-LABEL: define void @test_predicated_store(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[GEP_SRC:%.*]] = getelementptr inbounds i64, ptr [[SRC]], i64 [[IV]]
; CHECK-NEXT:    [[L:%.*]] = load i64, ptr [[GEP_SRC]], align 8
; CHECK-NEXT:    [[C:%.*]] = icmp eq i64 [[L]], 10
; CHECK-NEXT:    br i1 false, label %[[IF_END:.*]], label %[[IF_THEN:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[GEP_DST:%.*]] = getelementptr i64, ptr [[DST]], i64 [[IV]]
; CHECK-NEXT:    store i64 0, ptr [[GEP_DST]], align 8
; CHECK-NEXT:    [[GEP_DST_OFF:%.*]] = getelementptr i8, ptr [[GEP_DST]], i64 -31984
; CHECK-NEXT:    store i64 0, ptr [[GEP_DST_OFF]], align 8
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[GEP_DST_1:%.*]] = getelementptr i64, ptr [[DST]], i64 [[IV]]
; CHECK-NEXT:    store i64 0, ptr [[GEP_DST_1]], align 8
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 20
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i64 [[IV_NEXT]], 256
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %gep.src = getelementptr inbounds i64, ptr %src, i64 %iv
  %l = load i64, ptr %gep.src, align 8
  %c = icmp eq i64 %l, 10
  br i1 false, label %if.end, label %if.then

if.then:
  %gep.dst = getelementptr i64, ptr %dst, i64 %iv
  store i64 0, ptr %gep.dst, align 8
  %gep.dst.off = getelementptr i8, ptr %gep.dst, i64 -31984
  store i64 0, ptr %gep.dst.off, align 8
  br label %loop.latch

if.end:
  %gep.dst.1 = getelementptr i64, ptr %dst, i64 %iv
  store i64 0, ptr %gep.dst.1, align 8
  br label %loop.latch

loop.latch:
  %iv.next = add i64 %iv, 20
  %ec = icmp ne i64 %iv.next, 256
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

attributes #0 = { "target-cpu"="neoverse-512tvb" }
