; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=irce -S < %s 2>&1 | FileCheck %s

; Make sure we don't crash.
define void @pr89959() {
; CHECK-LABEL: define void @pr89959() {
; CHECK-NEXT:  top:
; CHECK-NEXT:    br label [[L3:%.*]]
; CHECK:       L3:
; CHECK-NEXT:    [[VALUE_PHI:%.*]] = phi ptr [ null, [[TOP:%.*]] ], [ [[TMP0:%.*]], [[L13:%.*]] ]
; CHECK-NEXT:    [[TMP0]] = getelementptr i8, ptr [[VALUE_PHI]], i64 8
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ule ptr [[VALUE_PHI]], null
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[L13]], label [[L15:%.*]]
; CHECK:       L13:
; CHECK-NEXT:    br label [[L3]]
; CHECK:       L15:
; CHECK-NEXT:    ret void
;
top:
  br label %L3

L3:
  %value_phi = phi ptr [ null, %top ], [ %0, %L13 ]
  %0 = getelementptr i8, ptr %value_phi, i64 8
  %.not = icmp ule ptr %value_phi, null
  br i1 %.not, label %L13, label %L15

L13:
  br label %L3

L15:
  ret void
}
