; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -o - -verify-machineinstrs -global-isel -stop-after=irtranslator -fp-contract=fast %s | FileCheck %s --check-prefix=FPFAST
; RUN: llc -o - -verify-machineinstrs -global-isel -stop-after=irtranslator -fp-contract=off %s | FileCheck %s --check-prefix=FPOFF
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "aarch64--"

define float @test_fmuladd(float %x, float %y, float %z) {
  ; FPFAST-LABEL: name: test_fmuladd
  ; FPFAST: bb.1 (%ir-block.0):
  ; FPFAST-NEXT:   liveins: $s0, $s1, $s2
  ; FPFAST-NEXT: {{  $}}
  ; FPFAST-NEXT:   [[COPY:%[0-9]+]]:_(f32) = COPY $s0
  ; FPFAST-NEXT:   [[COPY1:%[0-9]+]]:_(f32) = COPY $s1
  ; FPFAST-NEXT:   [[COPY2:%[0-9]+]]:_(f32) = COPY $s2
  ; FPFAST-NEXT:   [[FMA:%[0-9]+]]:_(f32) = G_FMA [[COPY]], [[COPY1]], [[COPY2]]
  ; FPFAST-NEXT:   $s0 = COPY [[FMA]](f32)
  ; FPFAST-NEXT:   RET_ReallyLR implicit $s0
  ;
  ; FPOFF-LABEL: name: test_fmuladd
  ; FPOFF: bb.1 (%ir-block.0):
  ; FPOFF-NEXT:   liveins: $s0, $s1, $s2
  ; FPOFF-NEXT: {{  $}}
  ; FPOFF-NEXT:   [[COPY:%[0-9]+]]:_(f32) = COPY $s0
  ; FPOFF-NEXT:   [[COPY1:%[0-9]+]]:_(f32) = COPY $s1
  ; FPOFF-NEXT:   [[COPY2:%[0-9]+]]:_(f32) = COPY $s2
  ; FPOFF-NEXT:   [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[COPY]], [[COPY1]]
  ; FPOFF-NEXT:   [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[COPY2]]
  ; FPOFF-NEXT:   $s0 = COPY [[FADD]](f32)
  ; FPOFF-NEXT:   RET_ReallyLR implicit $s0
  %res = call float @llvm.fmuladd.f32(float %x, float %y, float %z)
  ret float %res
}

; Function Attrs: nounwind readnone speculatable
declare float @llvm.fmuladd.f32(float, float, float) #0

attributes #0 = { nounwind readnone speculatable }
