; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc -mtriple=aarch64 -global-isel -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-GI



define i64 @sub_same_op(i64 %a) {
; CHECK-LABEL: sub_same_op:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    ret
entry:
; Fold x sub x -> 0
  %sub1 = sub i64 %a, %a
  ret i64 %sub1
}

define i64 @xor_same_op(i64 %a) {
; CHECK-LABEL: xor_same_op:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    ret
entry:
; Fold x xor x -> 0
  %xor1 = xor i64 %a, %a
  ret i64 %xor1
}


;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-GI: {{.*}}
; CHECK-SD: {{.*}}
