; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @test(ptr %cv, i32 %add72.i1848) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[CV:%.*]], i32 [[ADD72_I1848:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[STATE:%.*]] = alloca [16 x i32], align 16
; CHECK-NEXT:    [[DOTNOT435_I:%.*]] = icmp ugt ptr [[STATE]], [[CV]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[DOTNOT435_I]])
; CHECK-NEXT:    [[OR_I3888:%.*]] = call i32 @llvm.fshl.i32(i32 [[ADD72_I1848]], i32 1, i32 1)
; CHECK-NEXT:    [[ARRAYIDX202_I:%.*]] = getelementptr i8, ptr [[CV]], i64 16
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX202_I]], align 4
; CHECK-NEXT:    [[XOR_I1686:%.*]] = xor i32 [[OR_I3888]], [[TMP0]]
; CHECK-NEXT:    [[OR_I38946:%.*]] = call i32 @llvm.fshl.i32(i32 [[XOR_I1686]], i32 1, i32 1)
; CHECK-NEXT:    [[OR_I3892:%.*]] = call i32 @llvm.fshl.i32(i32 [[OR_I38946]], i32 1, i32 1)
; CHECK-NEXT:    [[ARRAYIDX270_I:%.*]] = getelementptr i8, ptr [[STATE]], i64 40
; CHECK-NEXT:    store i32 [[OR_I3892]], ptr [[ARRAYIDX270_I]], align 8
; CHECK-NEXT:    [[ADD105_I1737:%.*]] = add i32 [[OR_I3888]], [[ADD72_I1848]]
; CHECK-NEXT:    [[OR_I3898:%.*]] = call i32 @llvm.fshl.i32(i32 [[ADD72_I1848]], i32 1, i32 1)
; CHECK-NEXT:    [[ADD38_I1654:%.*]] = or i32 [[ADD105_I1737]], [[OR_I3898]]
; CHECK-NEXT:    [[OR_I3897:%.*]] = call i32 @llvm.fshl.i32(i32 [[ADD38_I1654]], i32 1, i32 1)
; CHECK-NEXT:    [[OR_I3896:%.*]] = call i32 @llvm.fshl.i32(i32 [[OR_I3897]], i32 1, i32 1)
; CHECK-NEXT:    [[ARRAYIDX287_I:%.*]] = getelementptr i8, ptr [[STATE]], i64 48
; CHECK-NEXT:    store i32 [[OR_I3896]], ptr [[ARRAYIDX287_I]], align 16
; CHECK-NEXT:    [[ARRAYIDX281_I:%.*]] = getelementptr i8, ptr [[STATE]], i64 44
; CHECK-NEXT:    store i32 [[OR_I3896]], ptr [[ARRAYIDX281_I]], align 4
; CHECK-NEXT:    [[ARRAYIDX192_I:%.*]] = getelementptr i8, ptr [[CV]], i64 12
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX192_I]], align 4
; CHECK-NEXT:    [[OR_I3906:%.*]] = call i32 @llvm.fshl.i32(i32 [[TMP1]], i32 1, i32 1)
; CHECK-NEXT:    [[OR_I3875:%.*]] = lshr i32 [[ADD72_I1848]], 1
; CHECK-NEXT:    [[XOR54_I:%.*]] = xor i32 [[OR_I3906]], [[OR_I3875]]
; CHECK-NEXT:    [[OR_I3905:%.*]] = call i32 @llvm.fshl.i32(i32 [[XOR54_I]], i32 1, i32 1)
; CHECK-NEXT:    [[XOR88_I:%.*]] = or i32 [[OR_I3905]], 1
; CHECK-NEXT:    [[OR_I3904:%.*]] = call i32 @llvm.fshl.i32(i32 [[XOR88_I]], i32 [[XOR88_I]], i32 1)
; CHECK-NEXT:    [[ARRAYIDX259_I:%.*]] = getelementptr i8, ptr [[STATE]], i64 36
; CHECK-NEXT:    store i32 [[OR_I3904]], ptr [[ARRAYIDX259_I]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %state = alloca [16 x i32], align 16
  %.not435.i = icmp ugt ptr %state, %cv
  call void @llvm.assume(i1 %.not435.i)
  %or.i3888 = call i32 @llvm.fshl.i32(i32 %add72.i1848, i32 1, i32 1)
  %arrayidx202.i = getelementptr i8, ptr %cv, i64 16
  %0 = load i32, ptr %arrayidx202.i, align 4
  %xor.i1686 = xor i32 %or.i3888, %0
  %or.i38946 = call i32 @llvm.fshl.i32(i32 %xor.i1686, i32 1, i32 1)
  %or.i3892 = call i32 @llvm.fshl.i32(i32 %or.i38946, i32 1, i32 1)
  %arrayidx270.i = getelementptr i8, ptr %state, i64 40
  store i32 %or.i3892, ptr %arrayidx270.i, align 8
  %add105.i1737 = add i32 %or.i3888, %add72.i1848
  %or.i3898 = call i32 @llvm.fshl.i32(i32 %add72.i1848, i32 1, i32 1)
  %add38.i1654 = or i32 %add105.i1737, %or.i3898
  %or.i3897 = call i32 @llvm.fshl.i32(i32 %add38.i1654, i32 1, i32 1)
  %or.i3896 = call i32 @llvm.fshl.i32(i32 %or.i3897, i32 1, i32 1)
  %arrayidx287.i = getelementptr i8, ptr %state, i64 48
  store i32 %or.i3896, ptr %arrayidx287.i, align 16
  %arrayidx281.i = getelementptr i8, ptr %state, i64 44
  store i32 %or.i3896, ptr %arrayidx281.i, align 4
  %arrayidx192.i = getelementptr i8, ptr %cv, i64 12
  %1 = load i32, ptr %arrayidx192.i, align 4
  %or.i3906 = call i32 @llvm.fshl.i32(i32 %1, i32 1, i32 1)
  %or.i3875 = lshr i32 %add72.i1848, 1
  %xor54.i = xor i32 %or.i3906, %or.i3875
  %or.i3905 = call i32 @llvm.fshl.i32(i32 %xor54.i, i32 1, i32 1)
  %xor88.i = or i32 %or.i3905, 1
  %or.i3904 = call i32 @llvm.fshl.i32(i32 %xor88.i, i32 %xor88.i, i32 1)
  %arrayidx259.i = getelementptr i8, ptr %state, i64 36
  store i32 %or.i3904, ptr %arrayidx259.i, align 4
  ret void
}

declare i32 @llvm.fshl.i32(i32, i32, i32)
declare void @llvm.assume(i1 noundef)
