; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test(i32 %g, i1 %tobool1.not) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[G:%.*]], i1 [[TOBOOL1_NOT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[G_ADDR_0334:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[REASS_SUB35:%.*]], %[[J:.*]] ]
; CHECK-NEXT:    [[I_ADDR_032:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[SUB14:%.*]], %[[J]] ]
; CHECK-NEXT:    br i1 [[TOBOOL1_NOT]], label %[[IF_END:.*]], label %[[J]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[SUB3:%.*]] = add i32 [[G]], 1
; CHECK-NEXT:    [[REM6:%.*]] = srem i32 1, [[G]]
; CHECK-NEXT:    [[SUB8:%.*]] = add i32 [[REM6]], 1
; CHECK-NEXT:    [[REM10:%.*]] = srem i32 1, [[G]]
; CHECK-NEXT:    [[SUB11:%.*]] = add i32 [[REM10]], 1
; CHECK-NEXT:    [[SUB12:%.*]] = add i32 [[SUB11]], [[G]]
; CHECK-NEXT:    br label %[[J]]
; CHECK:       [[J]]:
; CHECK-NEXT:    [[I_ADDR_1:%.*]] = phi i32 [ [[I_ADDR_032]], %[[WHILE_BODY]] ], [ [[SUB8]], %[[IF_END]] ]
; CHECK-NEXT:    [[G_ADDR_1:%.*]] = phi i32 [ [[G_ADDR_0334]], %[[WHILE_BODY]] ], [ [[SUB12]], %[[IF_END]] ]
; CHECK-NEXT:    [[F_1:%.*]] = phi i32 [ [[G]], %[[WHILE_BODY]] ], [ [[SUB3]], %[[IF_END]] ]
; CHECK-NEXT:    [[I_ADDR_1_FR11:%.*]] = freeze i32 [[I_ADDR_1]]
; CHECK-NEXT:    [[DIV:%.*]] = select i1 [[TOBOOL1_NOT]], i32 [[I_ADDR_1_FR11]], i32 0
; CHECK-NEXT:    [[SUB14]] = or i32 [[DIV]], [[G]]
; CHECK-NEXT:    [[F_1_FR10:%.*]] = freeze i32 [[F_1]]
; CHECK-NEXT:    [[DIV16:%.*]] = select i1 [[TOBOOL1_NOT]], i32 [[F_1_FR10]], i32 0
; CHECK-NEXT:    [[REASS_SUB35]] = or i32 [[DIV16]], [[G_ADDR_1]]
; CHECK-NEXT:    br label %[[WHILE_BODY]]
;
entry:
  br label %while.body

while.body:
  %g.addr.0334 = phi i32 [ 0, %entry ], [ %reass.sub35, %j ]
  %i.addr.032 = phi i32 [ 0, %entry ], [ %sub14, %j ]
  br i1 %tobool1.not, label %if.end, label %j

if.end:
  %sub3 = add i32 %g, 1
  %rem6 = srem i32 1, %g
  %sub8 = add i32 %rem6, 1
  %rem10 = srem i32 1, %g
  %sub11 = add i32 %rem10, 1
  %sub12 = add i32 %sub11, %g
  br label %j

j:
  %i.addr.1 = phi i32 [ %i.addr.032, %while.body ], [ %sub8, %if.end ]
  %g.addr.1 = phi i32 [ %g.addr.0334, %while.body ], [ %sub12, %if.end ]
  %f.1 = phi i32 [ %g, %while.body ], [ %sub3, %if.end ]
  %i.addr.1.fr11 = freeze i32 %i.addr.1
  %div = select i1 %tobool1.not, i32 %i.addr.1.fr11, i32 0
  %sub14 = or i32 %div, %g
  %f.1.fr10 = freeze i32 %f.1
  %div16 = select i1 %tobool1.not, i32 %f.1.fr10, i32 0
  %reass.sub35 = or i32 %div16, %g.addr.1
  br label %while.body
}
