// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -target-cpu gfx1200 -emit-llvm -fcuda-is-device -o - %s | FileCheck %s --check-prefix=CHECK-GFX1200

#define __device__ __attribute__((device))

typedef float    v8f   __attribute__((ext_vector_type(8)));
typedef _Float16 v8h   __attribute__((ext_vector_type(8)));

// CHECK-GFX1200-LABEL: define dso_local void @_Z47test_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12_hipPDv8_fDv8_DF16_S1_S_(
// CHECK-GFX1200-SAME: ptr noundef [[OUT:%.*]], <8 x half> noundef [[A:%.*]], <8 x half> noundef [[B:%.*]], <8 x float> noundef [[C:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-GFX1200-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1200-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-GFX1200-NEXT:    [[A_ADDR:%.*]] = alloca <8 x half>, align 16, addrspace(5)
// CHECK-GFX1200-NEXT:    [[B_ADDR:%.*]] = alloca <8 x half>, align 16, addrspace(5)
// CHECK-GFX1200-NEXT:    [[C_ADDR:%.*]] = alloca <8 x float>, align 32, addrspace(5)
// CHECK-GFX1200-NEXT:    [[OUT_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[OUT_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    [[A_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[A_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    [[B_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[B_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    [[C_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[C_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    store ptr [[OUT]], ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-GFX1200-NEXT:    store <8 x half> [[A]], ptr [[A_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    store <8 x half> [[B]], ptr [[B_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    store <8 x float> [[C]], ptr [[C_ADDR_ASCAST]], align 32
// CHECK-GFX1200-NEXT:    [[TMP0:%.*]] = load <8 x half>, ptr [[A_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    [[TMP1:%.*]] = load <8 x half>, ptr [[B_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    [[TMP2:%.*]] = load <8 x float>, ptr [[C_ADDR_ASCAST]], align 32
// CHECK-GFX1200-NEXT:    [[TMP3:%.*]] = call contract <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v8f16(<8 x half> [[TMP0]], <8 x half> [[TMP1]], <8 x float> [[TMP2]])
// CHECK-GFX1200-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-GFX1200-NEXT:    store <8 x float> [[TMP3]], ptr [[TMP4]], align 32
// CHECK-GFX1200-NEXT:    ret void
//
__device__ void test_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12_hip(v8f* out, v8h a, v8h b, v8f c) {
  *out = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(a, b, c);
}

// CHECK-GFX1200-LABEL: define dso_local void @_Z47test_amdgcn_wmma_f16_16x16x16_f16_w32_gfx12_hipPDv8_DF16_S_S_S_(
// CHECK-GFX1200-SAME: ptr noundef [[OUT:%.*]], <8 x half> noundef [[A:%.*]], <8 x half> noundef [[B:%.*]], <8 x half> noundef [[C:%.*]]) #[[ATTR0]] {
// CHECK-GFX1200-NEXT:  [[ENTRY:.*:]]
// CHECK-GFX1200-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-GFX1200-NEXT:    [[A_ADDR:%.*]] = alloca <8 x half>, align 16, addrspace(5)
// CHECK-GFX1200-NEXT:    [[B_ADDR:%.*]] = alloca <8 x half>, align 16, addrspace(5)
// CHECK-GFX1200-NEXT:    [[C_ADDR:%.*]] = alloca <8 x half>, align 16, addrspace(5)
// CHECK-GFX1200-NEXT:    [[OUT_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[OUT_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    [[A_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[A_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    [[B_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[B_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    [[C_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[C_ADDR]] to ptr
// CHECK-GFX1200-NEXT:    store ptr [[OUT]], ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-GFX1200-NEXT:    store <8 x half> [[A]], ptr [[A_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    store <8 x half> [[B]], ptr [[B_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    store <8 x half> [[C]], ptr [[C_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    [[TMP0:%.*]] = load <8 x half>, ptr [[A_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    [[TMP1:%.*]] = load <8 x half>, ptr [[B_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    [[TMP2:%.*]] = load <8 x half>, ptr [[C_ADDR_ASCAST]], align 16
// CHECK-GFX1200-NEXT:    [[TMP3:%.*]] = call contract <8 x half> @llvm.amdgcn.wmma.f16.16x16x16.f16.v8f16.v8f16(<8 x half> [[TMP0]], <8 x half> [[TMP1]], <8 x half> [[TMP2]], i1 false)
// CHECK-GFX1200-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-GFX1200-NEXT:    store <8 x half> [[TMP3]], ptr [[TMP4]], align 16
// CHECK-GFX1200-NEXT:    ret void
//
__device__ void test_amdgcn_wmma_f16_16x16x16_f16_w32_gfx12_hip(v8h* out, v8h a, v8h b, v8h c) {
  *out = __builtin_amdgcn_wmma_f16_16x16x16_f16_w32_gfx12(a, b, c);
}
