# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -o - %s -mtriple=x86_64-- -verify-cfiinstrs \
# RUN:     -run-pass=cfi-instr-inserter 2>&1 | FileCheck %s
# Test that CFI inserter inserts .cfi_restore properly for
# callee saved registers.
--- |
  define void @foo() {
    ret void
  }
...
---
name:            foo
body:             |
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   TEST8rr renamable $dil, renamable $dil, implicit-def $eflags, implicit killed $edi
  ; CHECK-NEXT:   JCC_1 %bb.2, 5, implicit killed $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP_1 %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   CFI_INSTRUCTION def_cfa_offset 16
  ; CHECK-NEXT:   CFI_INSTRUCTION offset $rbp, -16
  ; CHECK-NEXT:   CFI_INSTRUCTION def_cfa_register $rbp
  ; CHECK-NEXT:   CFI_INSTRUCTION offset $rbx, -24
  ; CHECK-NEXT:   CFI_INSTRUCTION def_cfa $rsp, 8
  ; CHECK-NEXT:   RET 0, $rax
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   CFI_INSTRUCTION restore $rbx
  ; CHECK-NEXT:   CFI_INSTRUCTION restore $rbp
  ; CHECK-NEXT:   RET 0, $rax
  bb.0:
    TEST8rr renamable $dil, renamable $dil, implicit-def $eflags, implicit killed $edi
    JCC_1 %bb.2, 5, implicit killed $eflags

  bb.1:
    JMP_1 %bb.3

  bb.2:
    CFI_INSTRUCTION def_cfa_offset 16
    CFI_INSTRUCTION offset $rbp, -16
    CFI_INSTRUCTION def_cfa_register $rbp
    CFI_INSTRUCTION offset $rbx, -24
    CFI_INSTRUCTION def_cfa $rsp, 8
    RET 0, $rax

  bb.3:
    RET 0, $rax

...
