; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define float @const_f32() {
; CHECK-LABEL: const_f32:
; CHECK:         .functype const_f32 () -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    f32.const $push0=, 0x1.91eb86p1
; CHECK-NEXT:    return $pop0
  ret float 3.14
}

define double @const_f64() {
; CHECK-LABEL: const_f64:
; CHECK:         .functype const_f64 () -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    f64.const $push0=, 0x1.91eb851eb851fp2
; CHECK-NEXT:    return $pop0
  ret double 6.28
}
