; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i8 @lshr_i8(i8 %x) {
; CHECK-LABEL: lshr_i8:
; CHECK:         .functype lshr_i8 (i32) -> (i32)
; CHECK-NEXT:    .local i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const $push3=, 5
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i32.const $push2=, 255
; CHECK-NEXT:    i32.and $push0=, $pop4, $pop2
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i32.shr_u $push1=, $pop0, $pop5
; CHECK-NEXT:    return $pop1
  %a = lshr i8 %x, 5
  ret i8 %a
}

define i8 @lshrv_i8(i8 %x, i8 %y) {
; CHECK-LABEL: lshrv_i8:
; CHECK:         .functype lshrv_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 255
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    local.get $push6=, 1
; CHECK-NEXT:    i32.const $push3=, 255
; CHECK-NEXT:    i32.and $push2=, $pop6, $pop3
; CHECK-NEXT:    i32.shr_u $push1=, $pop0, $pop2
; CHECK-NEXT:    return $pop1
  %a = lshr i8 %x, %y
  ret i8 %a
}

define i16 @lshr_i16(i16 %x) {
; CHECK-LABEL: lshr_i16:
; CHECK:         .functype lshr_i16 (i32) -> (i32)
; CHECK-NEXT:    .local i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const $push3=, 13
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i32.const $push2=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop4, $pop2
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i32.shr_u $push1=, $pop0, $pop5
; CHECK-NEXT:    return $pop1
  %a = lshr i16 %x, 13
  ret i16 %a
}

define i16 @lshrv_i16(i16 %x, i16 %y) {
; CHECK-LABEL: lshrv_i16:
; CHECK:         .functype lshrv_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    local.get $push6=, 1
; CHECK-NEXT:    i32.const $push3=, 65535
; CHECK-NEXT:    i32.and $push2=, $pop6, $pop3
; CHECK-NEXT:    i32.shr_u $push1=, $pop0, $pop2
; CHECK-NEXT:    return $pop1
  %a = lshr i16 %x, %y
  ret i16 %a
}

define i32 @lshr_i32(i32 %x) {
; CHECK-LABEL: lshr_i32:
; CHECK:         .functype lshr_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i32.const $push0=, 21
; CHECK-NEXT:    i32.shr_u $push1=, $pop2, $pop0
; CHECK-NEXT:    return $pop1
  %a = lshr i32 %x, 21
  ret i32 %a
}

define i32 @lshrv_i32(i32 %x, i32 %y) {
; CHECK-LABEL: lshrv_i32:
; CHECK:         .functype lshrv_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.shr_u $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = lshr i32 %x, %y
  ret i32 %a
}

define i64 @lshr_i64(i64 %x) {
; CHECK-LABEL: lshr_i64:
; CHECK:         .functype lshr_i64 (i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i64.const $push0=, 37
; CHECK-NEXT:    i64.shr_u $push1=, $pop2, $pop0
; CHECK-NEXT:    return $pop1
  %a = lshr i64 %x, 37
  ret i64 %a
}

define i64 @lshrv_i64(i64 %x, i64 %y) {
; CHECK-LABEL: lshrv_i64:
; CHECK:         .functype lshrv_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.shr_u $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = lshr i64 %x, %y
  ret i64 %a
}
