; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i8 @sub_i8(i8 %x, i8 %y) {
; CHECK-LABEL: sub_i8:
; CHECK:         .functype sub_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = sub i8 %x, %y
  ret i8 %a
}

define i16 @sub_i16(i16 %x, i16 %y) {
; CHECK-LABEL: sub_i16:
; CHECK:         .functype sub_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = sub i16 %x, %y
  ret i16 %a
}

define i32 @sub_i32(i32 %x, i32 %y) {
; CHECK-LABEL: sub_i32:
; CHECK:         .functype sub_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = sub i32 %x, %y
  ret i32 %a
}

define i64 @sub_i64(i64 %x, i64 %y) {
; CHECK-LABEL: sub_i64:
; CHECK:         .functype sub_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = sub i64 %x, %y
  ret i64 %a
}
