; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i1 @trunc_i32_i1(i32 %x) {
; CHECK-LABEL: trunc_i32_i1:
; CHECK:         .functype trunc_i32_i1 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push0=, 0
; CHECK-NEXT:    return $pop0
  %a = trunc i32 %x to i1
  ret i1 %a
}
define i1 @trunc_i64_i1(i64 %x) {
; CHECK-LABEL: trunc_i64_i1:
; CHECK:         .functype trunc_i64_i1 (i64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.wrap_i64 $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = trunc i64 %x to i1
  ret i1 %a
}

define i8 @trunc_i32_i8(i32 %x) {
; CHECK-LABEL: trunc_i32_i8:
; CHECK:         .functype trunc_i32_i8 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push0=, 0
; CHECK-NEXT:    return $pop0
  %a = trunc i32 %x to i8
  ret i8 %a
}
define i8 @trunc_i64_i8(i64 %x) {
; CHECK-LABEL: trunc_i64_i8:
; CHECK:         .functype trunc_i64_i8 (i64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.wrap_i64 $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = trunc i64 %x to i8
  ret i8 %a
}

define i16 @trunc_i32_i16(i32 %x) {
; CHECK-LABEL: trunc_i32_i16:
; CHECK:         .functype trunc_i32_i16 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push0=, 0
; CHECK-NEXT:    return $pop0
  %a = trunc i32 %x to i16
  ret i16 %a
}
define i16 @trunc_i64_i16(i64 %x) {
; CHECK-LABEL: trunc_i64_i16:
; CHECK:         .functype trunc_i64_i16 (i64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.wrap_i64 $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = trunc i64 %x to i16
  ret i16 %a
}

define i32 @trunc_i64_i32(i64 %x) {
; CHECK-LABEL: trunc_i64_i32:
; CHECK:         .functype trunc_i64_i32 (i64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.wrap_i64 $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = trunc i64 %x to i32
  ret i32 %a
}
