; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -S -passes=early-cse | FileCheck %s

; Test that when the load from %x is CSE'ed to %call1 by EarlyCSE, the !prof metadata
; is not dropped.
define i32 @indirect_call_value_profile_preserved(ptr %x, i32 %a, i32 %b, i32 %c)  {
; CHECK-LABEL: define i32 @indirect_call_value_profile_preserved
; CHECK-SAME: (ptr [[X:%.*]], i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @_Z10createTypei(i32 [[C]])
; CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[CALL]], align 8
; CHECK-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VFN]], align 8
; CHECK-NEXT:    [[CALL1:%.*]] = tail call i32 [[TMP0]](ptr [[CALL]], i32 [[A]], i32 [[B]]), !prof [[PROF0:![0-9]+]]
; CHECK-NEXT:    store i32 [[CALL1]], ptr [[X]], align 4
; CHECK-NEXT:    ret i32 [[CALL1]]
;
entry:
  %call = tail call ptr @_Z10createTypei(i32 %c)
  %vtable = load ptr, ptr %call, align 8
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 1
  %0 = load ptr, ptr %vfn, align 8
  %call1 = tail call i32 %0(ptr %call, i32 %a, i32 %b), !prof !0
  store i32 %call1, ptr %x
  %foo = load i32, ptr %x
  ret i32 %foo
}

declare ptr @_Z10createTypei(i32)

!0 =!{!"VP", i32 0, i64 1600, i64 12345, i64 1030, i64 678, i64 410}
