; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+fullfp16,+neon < %s | FileCheck %s --check-prefix=NEON-ENABLED
; RUN: llc -mtriple=aarch64 -mattr=+fullfp16,-neon < %s | FileCheck %s --check-prefix=NEON-DISABLED

define float @get_float() {
; NEON-ENABLED-LABEL: get_float:
; NEON-ENABLED:       // %bb.0:
; NEON-ENABLED-NEXT:    movi d0, #0000000000000000
; NEON-ENABLED-NEXT:    ret
;
; NEON-DISABLED-LABEL: get_float:
; NEON-DISABLED:       // %bb.0:
; NEON-DISABLED-NEXT:    fmov s0, wzr
; NEON-DISABLED-NEXT:    ret
  ret float 0.000000e+00
}

define double @get_double() {
; NEON-ENABLED-LABEL: get_double:
; NEON-ENABLED:       // %bb.0:
; NEON-ENABLED-NEXT:    movi d0, #0000000000000000
; NEON-ENABLED-NEXT:    ret
;
; NEON-DISABLED-LABEL: get_double:
; NEON-DISABLED:       // %bb.0:
; NEON-DISABLED-NEXT:    fmov d0, xzr
; NEON-DISABLED-NEXT:    ret
  ret double 0.000000e+00
}

define half @get_half() {
; NEON-ENABLED-LABEL: get_half:
; NEON-ENABLED:       // %bb.0:
; NEON-ENABLED-NEXT:    movi d0, #0000000000000000
; NEON-ENABLED-NEXT:    ret
;
; NEON-DISABLED-LABEL: get_half:
; NEON-DISABLED:       // %bb.0:
; NEON-DISABLED-NEXT:    fmov h0, wzr
; NEON-DISABLED-NEXT:    ret
  ret half 0.000000e+00
}
