; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -S -passes='coro-cleanup' | FileCheck %s

; Tests that resume or destroy a no-op coroutine can be erased; Finally, erase coro.noop if it has no users.
define void @erase(i1 %cond) personality i32 0 {
; CHECK-LABEL: define void @erase(
; CHECK-SAME: i1 [[COND:%.*]]) personality i32 0 {
; CHECK-NEXT:  [[DONE:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[DONE1:.*]], label %[[OTHER:.*]]
; CHECK:       [[DONE_UNREACHABLE:.*]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[DONE1]]:
; CHECK-NEXT:    ret void
; CHECK:       [[UNWIND:.*]]:
; CHECK-NEXT:    [[PAD:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            catch ptr null
; CHECK-NEXT:    call void @terminate()
; CHECK-NEXT:    unreachable
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    invoke void @terminate()
; CHECK-NEXT:            to label %[[DONE_UNREACHABLE]] unwind label %[[UNWIND]]
;
entry:
  br i1 %cond, label %coro, label %other

coro:
  %frame = call noundef ptr @llvm.coro.noop()
  %resume = call ptr @llvm.coro.subfn.addr(ptr %frame, i8 0)
  call fastcc void %resume(ptr %frame)
  %destroy = call ptr @llvm.coro.subfn.addr(ptr %frame, i8 1)
  invoke fastcc void %destroy(ptr %frame)
  to label %done unwind label %unwind

done:                                             ; preds = %coro, %other
  ret void

unwind:                                           ; preds = %coro, %other
  %phi = phi i32 [ 0, %coro ], [ 1, %other ]
  %pad = landingpad { ptr, i32 }
  catch ptr null
  call void @terminate()
  unreachable

other:
  invoke void @terminate() to label %done unwind label %unwind
}

; Tests the load-and-call pattern despite mismatched calling conventions. Prevent instcombine from breaking code.
define void @load() personality i32 0 {
; CHECK-LABEL: define void @load() personality i32 0 {
; CHECK-NEXT:  [[DONE:.*:]]
; CHECK-NEXT:    ret void
;
  %frame = call noundef ptr @llvm.coro.noop()
  %resume = load ptr, ptr %frame, align 8
  call void %resume(ptr %frame)
  %destroy.addr = getelementptr inbounds nuw i8, ptr %frame, i64 8
  %destroy = load ptr, ptr %destroy.addr, align 8
  invoke void %destroy(ptr %frame)
  to label %done unwind label %unwind

done:
  ret void

unwind:
  %pad = landingpad { ptr, i32 }
  catch ptr null
  call void @terminate()
  unreachable
}

declare void @terminate() noreturn
