; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -homogeneous-prolog-epilog < %s | FileCheck %s
target triple = "aarch64-linux"

declare void @g(ptr, ptr)

define void @f() minsize {
; CHECK-LABEL: f:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp x29, x30, [sp, #-16]!
; CHECK-NEXT:    str xzr, [sp, #-16]!
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset w30, -8
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    add x0, sp, #8
; CHECK-NEXT:    mov x1, sp
; CHECK-NEXT:    bl g
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    b OUTLINED_FUNCTION_EPILOG_TAIL_x30x29
entry:
  %p = alloca i32, align 8
  %n = alloca i64, align 8
  store i64 0, ptr %n, align 8
  call void @g(ptr %p, ptr %n)
  ret void
}
