@echo off
set "APOLLO_MSYS64_ROOT=C:\msys64"
set "APOLLO_MINGW_BIN=C:\msys64\clang64\bin"
set "APOLLO_LLVM_BIN=C:\msys64\clang64\bin"
set "APOLLO_GC_INCLUDE_DIR=C:\msys64\clang64\include"
set "APOLLO_GC_LIB_DIR=C:\msys64\clang64\lib"
set "APOLLO_SDL_INCLUDE_DIR=C:\msys64\clang64\include"
set "APOLLO_SDL_LIB_DIR=C:\msys64\clang64\lib"
set "PATH=%APOLLO_MINGW_BIN%;%PATH%"
