; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march xcore | FileCheck %s -check-prefixes=CHECK

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; CHECK-LABEL: naked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bl main
; CHECK-NEXT:    .cc_bottom naked.function
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; CHECK-LABEL: normal:
; CHECK:       # %bb.0:
; CHECK-NEXT:    entsp 2
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset 15, 0
; CHECK-NEXT:    stw r10, sp[1] # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 10, -4
; CHECK-NEXT:    ldaw r10, sp[0]
; CHECK-NEXT:    .cfi_def_cfa_register 10
; CHECK-NEXT:    extsp 1
; CHECK-NEXT:    bl main
; CHECK-NEXT:    ldaw sp, sp[1]
; CHECK-NEXT:    .cc_bottom normal.function
  call void @main()
  unreachable
}
