; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare i8 @llvm.ctpop.i8(i8)
declare i16 @llvm.ctpop.i16(i16)
declare i32 @llvm.ctpop.i32(i32)
declare i64 @llvm.ctpop.i64(i64)

define i8 @ctpop_i8(i8 %x) {
; CHECK-LABEL: ctpop_i8:
; CHECK:         .functype ctpop_i8 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.const $push2=, 255
; CHECK-NEXT:    i32.and $push0=, $pop3, $pop2
; CHECK-NEXT:    i32.popcnt $push1=, $pop0
; CHECK-NEXT:    return $pop1
  %a = call i8 @llvm.ctpop.i8(i8 %x)
  ret i8 %a
}

define i16 @ctpop_i16(i16 %x) {
; CHECK-LABEL: ctpop_i16:
; CHECK:         .functype ctpop_i16 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.const $push2=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop3, $pop2
; CHECK-NEXT:    i32.popcnt $push1=, $pop0
; CHECK-NEXT:    return $pop1
  %a = call i16 @llvm.ctpop.i16(i16 %x)
  ret i16 %a
}

define i32 @ctpop_i32(i32 %x) {
; CHECK-LABEL: ctpop_i32:
; CHECK:         .functype ctpop_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.popcnt $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i32 @llvm.ctpop.i32(i32 %x)
  ret i32 %a
}

define i64 @ctpop_i64(i64 %x) {
; CHECK-LABEL: ctpop_i64:
; CHECK:         .functype ctpop_i64 (i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i64.popcnt $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i64 @llvm.ctpop.i64(i64 %x)
  ret i64 %a
}
