; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i8 @mul_i8(i8 %x, i8 %y) {
; CHECK-LABEL: mul_i8:
; CHECK:         .functype mul_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.mul $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = mul i8 %x, %y
  ret i8 %a
}

define i16 @mul_i16(i16 %x, i16 %y) {
; CHECK-LABEL: mul_i16:
; CHECK:         .functype mul_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.mul $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = mul i16 %x, %y
  ret i16 %a
}

define i32 @mul_i32(i32 %x, i32 %y) {
; CHECK-LABEL: mul_i32:
; CHECK:         .functype mul_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.mul $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = mul i32 %x, %y
  ret i32 %a
}

define i64 @mul_i64(i64 %x, i64 %y) {
; CHECK-LABEL: mul_i64:
; CHECK:         .functype mul_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.mul $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = mul i64 %x, %y
  ret i64 %a
}
